### ISSUE TITLE
README/minizip.md question: what's the difference of this and minizip2?

### ISSUE THREAD

**Issue by ell1e** [luapower/minizip#3]
README/minizip.md question: what's the difference of this repo and [minizip2](https://github.com/luapower/minizip2/blob/master/minizip2.md)? While the files are different they look similar in purpose, and the minizip2 readme looks a bit broken in the github web preview for some reason.

**Comment by capr** [comment]
minizip binds v1 of the minizip C library, while minizip2 binds v2. As for feature differences, see https://luapower.com/minizip2 vs https://luapower.com/minizip or google for the C library.

**Comment by capr** [comment]
the .md files are not broken, just a different markdown dialect (pandoc, not github's), and they're purposed for luapower.com, not github.

**Comment by capr** [comment]
btw, on the right side of every repo there's a link to the real webpage of the repo which is on luapower.com (seems like github is trying hard to de-emphasize those links by moving them to the right sidebar)
